// Copyright 2026 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: github.com/openconfig/bootz/server/tests/proto/test.proto

package test

import (
	bootz "github.com/openconfig/bootz/proto/bootz"
	authz "github.com/openconfig/gnsi/authz"
	pathz "github.com/openconfig/gnsi/pathz"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Top level message that contains all the parameters for a Bootz test. This
// message is used to configure the Bootz SUT and the DUT.
type TestParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hostname of the DUT. This uniquely identifies the DUT.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The OS image that should be installed on the DUT.
	OsImage *OSImage `protobuf:"bytes,2,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	// The bootstrap data that should be returned to the DUT by the Bootz SUT
	// as part of the test. This may be a valid config (for use in positive
	// test cases) or it may be an invalid config (for use in negative test
	// cases). If the latter, the test should include recovery bootstrap data
	// to allow the DUT to be recovered after the test. See the
	// `recovery_data` field below for more details.
	BootstrapData *BootstrapData `protobuf:"bytes,3,opt,name=bootstrap_data,json=bootstrapData,proto3" json:"bootstrap_data,omitempty"`
	// The security artifacts that the Bootz SUT should use during bootstrapping.
	SecurityArtifacts *SecurityArtifacts `protobuf:"bytes,4,opt,name=security_artifacts,json=securityArtifacts,proto3" json:"security_artifacts,omitempty"`
	// Information about the DUT's interfaces for use during DHCP and Bootz.
	InterfaceInfo *InterfaceInfo `protobuf:"bytes,5,opt,name=interface_info,json=interfaceInfo,proto3" json:"interface_info,omitempty"`
	// The boot mode that the Bootz SUT should use during bootstrapping. If set to
	// SECURE, the SUT must be configured with ownership vouchers and an ownership
	// certificate to provide to the DUT. If unset, the test will use SECURE
	// mode.
	BootMode bootz.BootMode `protobuf:"varint,6,opt,name=boot_mode,json=bootMode,proto3,enum=bootz.BootMode" json:"boot_mode,omitempty"`
	// The expected state of the DUT after bootstrapping.
	WantBootzState *BootzState `protobuf:"bytes,7,opt,name=want_bootz_state,json=wantBootzState,proto3" json:"want_bootz_state,omitempty"`
	// If this field is not set, the Bootz SUT will not provide any additional
	// bootstrap data after the test, and it will be the responsibility of the
	// test runner to recover the DUT through other means.
	RecoveryData *DUTRecoveryData `protobuf:"bytes,8,opt,name=recovery_data,json=recoveryData,proto3" json:"recovery_data,omitempty"`
	// The duration of the test. If the DUT has not reported the expected final
	// status by the time this duration has elapsed, the test will be marked as
	// failed and the Bootz SUT will provide the `recovery_data` if it
	// is set.
	Timeout       *durationpb.Duration `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestParameters) Reset() {
	*x = TestParameters{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestParameters) ProtoMessage() {}

func (x *TestParameters) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestParameters.ProtoReflect.Descriptor instead.
func (*TestParameters) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestParameters) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TestParameters) GetOsImage() *OSImage {
	if x != nil {
		return x.OsImage
	}
	return nil
}

func (x *TestParameters) GetBootstrapData() *BootstrapData {
	if x != nil {
		return x.BootstrapData
	}
	return nil
}

func (x *TestParameters) GetSecurityArtifacts() *SecurityArtifacts {
	if x != nil {
		return x.SecurityArtifacts
	}
	return nil
}

func (x *TestParameters) GetInterfaceInfo() *InterfaceInfo {
	if x != nil {
		return x.InterfaceInfo
	}
	return nil
}

func (x *TestParameters) GetBootMode() bootz.BootMode {
	if x != nil {
		return x.BootMode
	}
	return bootz.BootMode(0)
}

func (x *TestParameters) GetWantBootzState() *BootzState {
	if x != nil {
		return x.WantBootzState
	}
	return nil
}

func (x *TestParameters) GetRecoveryData() *DUTRecoveryData {
	if x != nil {
		return x.RecoveryData
	}
	return nil
}

func (x *TestParameters) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Contains data used for recovering the DUT after a test. Any fields set
// in these messages will overwrite the existing DUT data for the test. Fields
// that are unset will be ignored and the existing DUT data for those fields
// will be retained. For example, if the `recovery_data` field is set with a
// `BootstrapData` message that has only the `boot_config` field set, then only
// the boot config will be overwritten on the DUT and the credentials, pathz
// policy, authz policy and certz profiles from the original `bootstrap_data`
// will be retained.
type DUTRecoveryData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recovery bootstrap data.
	RecoveryBootstrapData *BootstrapData `protobuf:"bytes,1,opt,name=recovery_bootstrap_data,json=recoveryBootstrapData,proto3" json:"recovery_bootstrap_data,omitempty"`
	// Recovery OS image data.
	RecoveryOsImage *OSImage `protobuf:"bytes,2,opt,name=recovery_os_image,json=recoveryOsImage,proto3" json:"recovery_os_image,omitempty"`
	// Recovery security artifact data.
	RecoverySecurityArtifacts *SecurityArtifacts `protobuf:"bytes,3,opt,name=recovery_security_artifacts,json=recoverySecurityArtifacts,proto3" json:"recovery_security_artifacts,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DUTRecoveryData) Reset() {
	*x = DUTRecoveryData{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DUTRecoveryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DUTRecoveryData) ProtoMessage() {}

func (x *DUTRecoveryData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DUTRecoveryData.ProtoReflect.Descriptor instead.
func (*DUTRecoveryData) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *DUTRecoveryData) GetRecoveryBootstrapData() *BootstrapData {
	if x != nil {
		return x.RecoveryBootstrapData
	}
	return nil
}

func (x *DUTRecoveryData) GetRecoveryOsImage() *OSImage {
	if x != nil {
		return x.RecoveryOsImage
	}
	return nil
}

func (x *DUTRecoveryData) GetRecoverySecurityArtifacts() *SecurityArtifacts {
	if x != nil {
		return x.RecoverySecurityArtifacts
	}
	return nil
}

// Contains information about an OS image on the DUT.
type OSImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the OS.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the OS.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The location of the OS image. This can be an HTTP URL or any other type of
	// URI that can be used to download the OS image.
	DownloadUri string `protobuf:"bytes,3,opt,name=download_uri,json=downloadUri,proto3" json:"download_uri,omitempty"`
	// If true, the SUT will fetch the OS image from this location, load it to
	// memory and make it available to the DUT via an HTTP URL. This is useful
	// for cases where the above download_uri is not accessible to the DUT, but
	// is accessible to the SUT.
	ReuploadToSut bool `protobuf:"varint,4,opt,name=reupload_to_sut,json=reuploadToSut,proto3" json:"reupload_to_sut,omitempty"`
	// The hash of the OS image. The format of this field is a
	// `hex-string`, identified in RFC6991 as "A hexadecimal string with
	// octets represented as hex digits separated by colons.
	// The canonical representation uses lowercase characters."
	// E.g.: "d9:a5:d1:0b:09:fa:4e:96:f2:40:bf:6a:82:f5"
	OsImageHash string `protobuf:"bytes,5,opt,name=os_image_hash,json=osImageHash,proto3" json:"os_image_hash,omitempty"`
	// The identity of the hash algorithm used. These hash identities are
	// defined in sZTP RFC 8572. There is currently only one hash algorithm
	// defined in this spec:
	// `ietf-sztp-conveyed-info:sha-256` for the SHA 256 algorithm.
	HashAlgorithm string `protobuf:"bytes,6,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSImage) Reset() {
	*x = OSImage{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSImage) ProtoMessage() {}

func (x *OSImage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSImage.ProtoReflect.Descriptor instead.
func (*OSImage) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{2}
}

func (x *OSImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSImage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSImage) GetDownloadUri() string {
	if x != nil {
		return x.DownloadUri
	}
	return ""
}

func (x *OSImage) GetReuploadToSut() bool {
	if x != nil {
		return x.ReuploadToSut
	}
	return false
}

func (x *OSImage) GetOsImageHash() string {
	if x != nil {
		return x.OsImageHash
	}
	return ""
}

func (x *OSImage) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

// Contains information about the bootstrap data that the Bootz SUT should
// return to the DUT.
type BootstrapData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The boot config to be returned to the DUT by the Bootz SUT.
	BootConfig *bootz.BootConfig `protobuf:"bytes,1,opt,name=boot_config,json=bootConfig,proto3" json:"boot_config,omitempty"`
	// The credentials to be returned to the DUT by the Bootz SUT.
	Credentials *bootz.Credentials `protobuf:"bytes,2,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// The pathz policy to be returned to the DUT by the Bootz SUT.
	Pathz *pathz.UploadRequest `protobuf:"bytes,3,opt,name=pathz,proto3" json:"pathz,omitempty"`
	// The authz policy to be returned to the DUT by the Bootz SUT.
	Authz *authz.UploadRequest `protobuf:"bytes,4,opt,name=authz,proto3" json:"authz,omitempty"`
	// The certz profiles to be returned to the DUT by the Bootz SUT.
	CertzProfiles *bootz.CertzProfiles `protobuf:"bytes,5,opt,name=certz_profiles,json=certzProfiles,proto3" json:"certz_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapData) Reset() {
	*x = BootstrapData{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapData) ProtoMessage() {}

func (x *BootstrapData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapData.ProtoReflect.Descriptor instead.
func (*BootstrapData) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapData) GetBootConfig() *bootz.BootConfig {
	if x != nil {
		return x.BootConfig
	}
	return nil
}

func (x *BootstrapData) GetCredentials() *bootz.Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *BootstrapData) GetPathz() *pathz.UploadRequest {
	if x != nil {
		return x.Pathz
	}
	return nil
}

func (x *BootstrapData) GetAuthz() *authz.UploadRequest {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *BootstrapData) GetCertzProfiles() *bootz.CertzProfiles {
	if x != nil {
		return x.CertzProfiles
	}
	return nil
}

// Contains information about the security artifacts that the Bootz SUT should
// use during bootstrapping. If not provided in this message, the Bootz SUT
// must attempt to fetch them from another source (e.g. a secure database). It
// is the responsibility of the test runner to ensure these artifacts are
// stored and handled securely.
type SecurityArtifacts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A mapping of control card serial number to Ownership Voucher that the Bootz
	// SUT should use during bootstrapping. The format of the value in this map is
	// a CMS message (RFC 5652).
	OwnershipVouchers map[string][]byte `protobuf:"bytes,1,rep,name=ownership_vouchers,json=ownershipVouchers,proto3" json:"ownership_vouchers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A mapping of control card serial number to TPM Endorsement Key (EK)
	// for use in the BootstrapStream HMAC challenge. The format of the value in
	// this map is a PEM-encoded RSA public key.
	Eks map[string][]byte `protobuf:"bytes,2,rep,name=eks,proto3" json:"eks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A mapping of control card serial number to TPM Platform Primary Key (PPK)
	// for use in the BootstrapStream HMAC challenge. The format of the value
	// in this map is a PEM-encoded RSA public key.
	Ppks map[string][]byte `protobuf:"bytes,3,rep,name=ppks,proto3" json:"ppks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The x509 certificate that the Bootz SUT should use to sign bootstrap
	// responses. This certificate must have a chain of trust leading up to the
	// Pinned Domain Cert that exists within the Ownership Voucher. The format of
	// this field is a PEM-encoded x509 certificate.
	OcCert string `protobuf:"bytes,4,opt,name=oc_cert,json=ocCert,proto3" json:"oc_cert,omitempty"`
	// The corresponding private key for the above OC certificate.
	// The format of this field is a PEM-encoded private key.
	OcPrivateKey string `protobuf:"bytes,5,opt,name=oc_private_key,json=ocPrivateKey,proto3" json:"oc_private_key,omitempty"`
	// A certificate that corresponds to the CA that signed the DUT's
	// IDevID certificate. This field should contain the CA that directly signed
	// the DUT's IDevID and not necessarily the Root CA. The format of this
	// field is a PEM-encoded x509 certificate.
	IdevidCa      string `protobuf:"bytes,6,opt,name=idevid_ca,json=idevidCa,proto3" json:"idevid_ca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityArtifacts) Reset() {
	*x = SecurityArtifacts{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityArtifacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityArtifacts) ProtoMessage() {}

func (x *SecurityArtifacts) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityArtifacts.ProtoReflect.Descriptor instead.
func (*SecurityArtifacts) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityArtifacts) GetOwnershipVouchers() map[string][]byte {
	if x != nil {
		return x.OwnershipVouchers
	}
	return nil
}

func (x *SecurityArtifacts) GetEks() map[string][]byte {
	if x != nil {
		return x.Eks
	}
	return nil
}

func (x *SecurityArtifacts) GetPpks() map[string][]byte {
	if x != nil {
		return x.Ppks
	}
	return nil
}

func (x *SecurityArtifacts) GetOcCert() string {
	if x != nil {
		return x.OcCert
	}
	return ""
}

func (x *SecurityArtifacts) GetOcPrivateKey() string {
	if x != nil {
		return x.OcPrivateKey
	}
	return ""
}

func (x *SecurityArtifacts) GetIdevidCa() string {
	if x != nil {
		return x.IdevidCa
	}
	return ""
}

// Contains information about the DUT's interfaces for use during DHCP and
// Bootz.
type InterfaceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address to assign to the DUT for the DHCP lease. For example,
	// "192.168.1.100" or "2001:db8::2".
	DhcpAddress string `protobuf:"bytes,1,opt,name=dhcp_address,json=dhcpAddress,proto3" json:"dhcp_address,omitempty"`
	// The default gateway for the DUT's management interface.
	// This will be provided in the DHCP lease. For example,
	// "192.168.1.1" or "2001:db8::1".
	DefaultGateway string `protobuf:"bytes,2,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	// The mask length for the DUT's management interface.
	// This will be provided in the DHCP lease. For example, "24" for IPv4 or
	// "120" for IPv6.
	MaskLength int32 `protobuf:"varint,3,opt,name=mask_length,json=maskLength,proto3" json:"mask_length,omitempty"`
	// Additional addresses (excluding the DHCP address) that the DUT may use to
	// communicate with the Bootz SUT. These are addresses that may be used for
	// subsequent gRPC connections to Bootz server after the initial connection.
	// For example, the DUT may use DHCP address `192.168.1.100` to make the
	// initial gRPC connection to Bootz server but the boot config may specify a
	// different address `192.168.1.200`. Either of these may be used by the
	// device to make the gRPC connection.
	AdditionalAddresses []string `protobuf:"bytes,4,rep,name=additional_addresses,json=additionalAddresses,proto3" json:"additional_addresses,omitempty"`
	// Name of out of band management interface(s) on the DUT. These will be used
	// to discover the MAC addresses to be used in the DHCP lease.
	ManagementInterfaceNames []string `protobuf:"bytes,5,rep,name=management_interface_names,json=managementInterfaceNames,proto3" json:"management_interface_names,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InterfaceInfo) Reset() {
	*x = InterfaceInfo{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceInfo) ProtoMessage() {}

func (x *InterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceInfo.ProtoReflect.Descriptor instead.
func (*InterfaceInfo) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceInfo) GetDhcpAddress() string {
	if x != nil {
		return x.DhcpAddress
	}
	return ""
}

func (x *InterfaceInfo) GetDefaultGateway() string {
	if x != nil {
		return x.DefaultGateway
	}
	return ""
}

func (x *InterfaceInfo) GetMaskLength() int32 {
	if x != nil {
		return x.MaskLength
	}
	return 0
}

func (x *InterfaceInfo) GetAdditionalAddresses() []string {
	if x != nil {
		return x.AdditionalAddresses
	}
	return nil
}

func (x *InterfaceInfo) GetManagementInterfaceNames() []string {
	if x != nil {
		return x.ManagementInterfaceNames
	}
	return nil
}

// Contains the expected state of the DUT after bootstrapping.
type BootzState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The expected last status of the SUT after Bootz. For positive test cases
	// this should be "BOOTZ_OK".
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootzState) Reset() {
	*x = BootzState{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootzState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootzState) ProtoMessage() {}

func (x *BootzState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootzState.ProtoReflect.Descriptor instead.
func (*BootzState) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP(), []int{6}
}

func (x *BootzState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_github_com_openconfig_bootz_server_tests_proto_test_proto protoreflect.FileDescriptor

const file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDesc = "" +
	"\n" +
	"9github.com/openconfig/bootz/server/tests/proto/test.proto\x12\x05bootz\x1a\x1egoogle/protobuf/duration.proto\x1a-github.com/openconfig/bootz/proto/bootz.proto\x1a,github.com/openconfig/gnsi/authz/authz.proto\x1a,github.com/openconfig/gnsi/pathz/pathz.proto\"\xf7\x03\n" +
	"\x0eTestParameters\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12)\n" +
	"\bos_image\x18\x02 \x01(\v2\x0e.bootz.OSImageR\aosImage\x12;\n" +
	"\x0ebootstrap_data\x18\x03 \x01(\v2\x14.bootz.BootstrapDataR\rbootstrapData\x12G\n" +
	"\x12security_artifacts\x18\x04 \x01(\v2\x18.bootz.SecurityArtifactsR\x11securityArtifacts\x12;\n" +
	"\x0einterface_info\x18\x05 \x01(\v2\x14.bootz.InterfaceInfoR\rinterfaceInfo\x12,\n" +
	"\tboot_mode\x18\x06 \x01(\x0e2\x0f.bootz.BootModeR\bbootMode\x12;\n" +
	"\x10want_bootz_state\x18\a \x01(\v2\x11.bootz.BootzStateR\x0ewantBootzState\x12;\n" +
	"\rrecovery_data\x18\b \x01(\v2\x16.bootz.DUTRecoveryDataR\frecoveryData\x123\n" +
	"\atimeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xf5\x01\n" +
	"\x0fDUTRecoveryData\x12L\n" +
	"\x17recovery_bootstrap_data\x18\x01 \x01(\v2\x14.bootz.BootstrapDataR\x15recoveryBootstrapData\x12:\n" +
	"\x11recovery_os_image\x18\x02 \x01(\v2\x0e.bootz.OSImageR\x0frecoveryOsImage\x12X\n" +
	"\x1brecovery_security_artifacts\x18\x03 \x01(\v2\x18.bootz.SecurityArtifactsR\x19recoverySecurityArtifacts\"\xcd\x01\n" +
	"\aOSImage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fdownload_uri\x18\x03 \x01(\tR\vdownloadUri\x12&\n" +
	"\x0freupload_to_sut\x18\x04 \x01(\bR\rreuploadToSut\x12\"\n" +
	"\ros_image_hash\x18\x05 \x01(\tR\vosImageHash\x12%\n" +
	"\x0ehash_algorithm\x18\x06 \x01(\tR\rhashAlgorithm\"\x9e\x02\n" +
	"\rBootstrapData\x122\n" +
	"\vboot_config\x18\x01 \x01(\v2\x11.bootz.BootConfigR\n" +
	"bootConfig\x124\n" +
	"\vcredentials\x18\x02 \x01(\v2\x12.bootz.CredentialsR\vcredentials\x122\n" +
	"\x05pathz\x18\x03 \x01(\v2\x1c.gnsi.pathz.v1.UploadRequestR\x05pathz\x122\n" +
	"\x05authz\x18\x04 \x01(\v2\x1c.gnsi.authz.v1.UploadRequestR\x05authz\x12;\n" +
	"\x0ecertz_profiles\x18\x05 \x01(\v2\x14.bootz.CertzProfilesR\rcertzProfiles\"\xf3\x03\n" +
	"\x11SecurityArtifacts\x12^\n" +
	"\x12ownership_vouchers\x18\x01 \x03(\v2/.bootz.SecurityArtifacts.OwnershipVouchersEntryR\x11ownershipVouchers\x123\n" +
	"\x03eks\x18\x02 \x03(\v2!.bootz.SecurityArtifacts.EksEntryR\x03eks\x126\n" +
	"\x04ppks\x18\x03 \x03(\v2\".bootz.SecurityArtifacts.PpksEntryR\x04ppks\x12\x17\n" +
	"\aoc_cert\x18\x04 \x01(\tR\x06ocCert\x12$\n" +
	"\x0eoc_private_key\x18\x05 \x01(\tR\focPrivateKey\x12\x1b\n" +
	"\tidevid_ca\x18\x06 \x01(\tR\bidevidCa\x1aD\n" +
	"\x16OwnershipVouchersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a6\n" +
	"\bEksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a7\n" +
	"\tPpksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xed\x01\n" +
	"\rInterfaceInfo\x12!\n" +
	"\fdhcp_address\x18\x01 \x01(\tR\vdhcpAddress\x12'\n" +
	"\x0fdefault_gateway\x18\x02 \x01(\tR\x0edefaultGateway\x12\x1f\n" +
	"\vmask_length\x18\x03 \x01(\x05R\n" +
	"maskLength\x121\n" +
	"\x14additional_addresses\x18\x04 \x03(\tR\x13additionalAddresses\x12<\n" +
	"\x1amanagement_interface_names\x18\x05 \x03(\tR\x18managementInterfaceNames\"$\n" +
	"\n" +
	"BootzState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06statusB5Z3github.com/openconfig/bootz/server/tests/proto/testb\x06proto3"

var (
	file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescOnce sync.Once
	file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescData []byte
)

func file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDesc), len(file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDesc)))
	})
	return file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDescData
}

var file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_github_com_openconfig_bootz_server_tests_proto_test_proto_goTypes = []any{
	(*TestParameters)(nil),      // 0: bootz.TestParameters
	(*DUTRecoveryData)(nil),     // 1: bootz.DUTRecoveryData
	(*OSImage)(nil),             // 2: bootz.OSImage
	(*BootstrapData)(nil),       // 3: bootz.BootstrapData
	(*SecurityArtifacts)(nil),   // 4: bootz.SecurityArtifacts
	(*InterfaceInfo)(nil),       // 5: bootz.InterfaceInfo
	(*BootzState)(nil),          // 6: bootz.BootzState
	nil,                         // 7: bootz.SecurityArtifacts.OwnershipVouchersEntry
	nil,                         // 8: bootz.SecurityArtifacts.EksEntry
	nil,                         // 9: bootz.SecurityArtifacts.PpksEntry
	(bootz.BootMode)(0),         // 10: bootz.BootMode
	(*durationpb.Duration)(nil), // 11: google.protobuf.Duration
	(*bootz.BootConfig)(nil),    // 12: bootz.BootConfig
	(*bootz.Credentials)(nil),   // 13: bootz.Credentials
	(*pathz.UploadRequest)(nil), // 14: gnsi.pathz.v1.UploadRequest
	(*authz.UploadRequest)(nil), // 15: gnsi.authz.v1.UploadRequest
	(*bootz.CertzProfiles)(nil), // 16: bootz.CertzProfiles
}
var file_github_com_openconfig_bootz_server_tests_proto_test_proto_depIdxs = []int32{
	2,  // 0: bootz.TestParameters.os_image:type_name -> bootz.OSImage
	3,  // 1: bootz.TestParameters.bootstrap_data:type_name -> bootz.BootstrapData
	4,  // 2: bootz.TestParameters.security_artifacts:type_name -> bootz.SecurityArtifacts
	5,  // 3: bootz.TestParameters.interface_info:type_name -> bootz.InterfaceInfo
	10, // 4: bootz.TestParameters.boot_mode:type_name -> bootz.BootMode
	6,  // 5: bootz.TestParameters.want_bootz_state:type_name -> bootz.BootzState
	1,  // 6: bootz.TestParameters.recovery_data:type_name -> bootz.DUTRecoveryData
	11, // 7: bootz.TestParameters.timeout:type_name -> google.protobuf.Duration
	3,  // 8: bootz.DUTRecoveryData.recovery_bootstrap_data:type_name -> bootz.BootstrapData
	2,  // 9: bootz.DUTRecoveryData.recovery_os_image:type_name -> bootz.OSImage
	4,  // 10: bootz.DUTRecoveryData.recovery_security_artifacts:type_name -> bootz.SecurityArtifacts
	12, // 11: bootz.BootstrapData.boot_config:type_name -> bootz.BootConfig
	13, // 12: bootz.BootstrapData.credentials:type_name -> bootz.Credentials
	14, // 13: bootz.BootstrapData.pathz:type_name -> gnsi.pathz.v1.UploadRequest
	15, // 14: bootz.BootstrapData.authz:type_name -> gnsi.authz.v1.UploadRequest
	16, // 15: bootz.BootstrapData.certz_profiles:type_name -> bootz.CertzProfiles
	7,  // 16: bootz.SecurityArtifacts.ownership_vouchers:type_name -> bootz.SecurityArtifacts.OwnershipVouchersEntry
	8,  // 17: bootz.SecurityArtifacts.eks:type_name -> bootz.SecurityArtifacts.EksEntry
	9,  // 18: bootz.SecurityArtifacts.ppks:type_name -> bootz.SecurityArtifacts.PpksEntry
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_bootz_server_tests_proto_test_proto_init() }
func file_github_com_openconfig_bootz_server_tests_proto_test_proto_init() {
	if File_github_com_openconfig_bootz_server_tests_proto_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDesc), len(file_github_com_openconfig_bootz_server_tests_proto_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_openconfig_bootz_server_tests_proto_test_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_bootz_server_tests_proto_test_proto_depIdxs,
		MessageInfos:      file_github_com_openconfig_bootz_server_tests_proto_test_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_bootz_server_tests_proto_test_proto = out.File
	file_github_com_openconfig_bootz_server_tests_proto_test_proto_goTypes = nil
	file_github_com_openconfig_bootz_server_tests_proto_test_proto_depIdxs = nil
}
