// Copyright 2026 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: github.com/openconfig/bootz/server/tests/proto/sut.proto

package sut

import (
	bootz "github.com/openconfig/bootz/proto/bootz"
	test "github.com/openconfig/bootz/server/tests/proto/test"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MAC addresses to associate with this DHCP lease. For modular devices, this
	// allows either control card to acquire the lease.
	MacAddresses []string `protobuf:"bytes,1,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	// The IP address to associate with this lease. Note, for a modular chassis
	// only the active control card will acquire the lease, so only one IP
	// address should be provided.
	// For example, "192.168.1.100" or "2001:db8::2".
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// The mask length of the lease IP address. For example, "24" for IPv4 or
	// "120" for IPv6.
	MaskLen int32 `protobuf:"varint,3,opt,name=mask_len,json=maskLen,proto3" json:"mask_len,omitempty"`
	// The gateway IP address. For example,"192.168.1.1" or "2001:db8::1".
	Gateway string `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// The address of the Bootz server to be included in the DHCP response. It
	// should have the format: bootz://<server_address>:<port>. For example:
	// * IPv6: bootz://[2001:db8::1]:12345
	// * IPv4: bootz://192.168.1.1:12345
	BootzServerAddress string `protobuf:"bytes,5,opt,name=bootz_server_address,json=bootzServerAddress,proto3" json:"bootz_server_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateLeaseRequest) Reset() {
	*x = CreateLeaseRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseRequest) ProtoMessage() {}

func (x *CreateLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateLeaseRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeaseRequest) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

func (x *CreateLeaseRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateLeaseRequest) GetMaskLen() int32 {
	if x != nil {
		return x.MaskLen
	}
	return 0
}

func (x *CreateLeaseRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *CreateLeaseRequest) GetBootzServerAddress() string {
	if x != nil {
		return x.BootzServerAddress
	}
	return ""
}

type CreateLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeaseResponse) Reset() {
	*x = CreateLeaseResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseResponse) ProtoMessage() {}

func (x *CreateLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseResponse.ProtoReflect.Descriptor instead.
func (*CreateLeaseResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{1}
}

type RemoveLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The MAC addresses to remove the DHCP lease for.
	MacAddresses  []string `protobuf:"bytes,1,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLeaseRequest) Reset() {
	*x = RemoveLeaseRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLeaseRequest) ProtoMessage() {}

func (x *RemoveLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLeaseRequest.ProtoReflect.Descriptor instead.
func (*RemoveLeaseRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveLeaseRequest) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

type RemoveLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLeaseResponse) Reset() {
	*x = RemoveLeaseResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLeaseResponse) ProtoMessage() {}

func (x *RemoveLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLeaseResponse.ProtoReflect.Descriptor instead.
func (*RemoveLeaseResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{3}
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details about the OS to be made available to the DUT. If `reupload_to_sut`
	// is true, the service should fetch the image from the provided URL and make
	// it available on a URL that the DUT can access. This final URL should be
	// included in the `image.url` field of the response. If `reupload_to_sut` is
	// false, the provided URL will be used directly in the `image.url` field of
	// the response.
	Image         *test.OSImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{4}
}

func (x *UploadRequest) GetImage() *test.OSImage {
	if x != nil {
		return x.Image
	}
	return nil
}

type UploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The final Bootz SoftwareImage that the Bootz controller SUT should provide
	// to the DUT during the Bootz test.
	Image         *bootz.SoftwareImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{5}
}

func (x *UploadResponse) GetImage() *bootz.SoftwareImage {
	if x != nil {
		return x.Image
	}
	return nil
}

type SetBootstrapDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The data to be used by the Bootz SUT during the Bootz test.
	BootstrapData *test.BootstrapData `protobuf:"bytes,1,opt,name=bootstrap_data,json=bootstrapData,proto3" json:"bootstrap_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootstrapDataRequest) Reset() {
	*x = SetBootstrapDataRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootstrapDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootstrapDataRequest) ProtoMessage() {}

func (x *SetBootstrapDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootstrapDataRequest.ProtoReflect.Descriptor instead.
func (*SetBootstrapDataRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{6}
}

func (x *SetBootstrapDataRequest) GetBootstrapData() *test.BootstrapData {
	if x != nil {
		return x.BootstrapData
	}
	return nil
}

type SetBootstrapDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBootstrapDataResponse) Reset() {
	*x = SetBootstrapDataResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBootstrapDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBootstrapDataResponse) ProtoMessage() {}

func (x *SetBootstrapDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBootstrapDataResponse.ProtoReflect.Descriptor instead.
func (*SetBootstrapDataResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{7}
}

type SetSecurityArtifactsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The security artifacts to be used by the Bootz SUT during the Bootz test.
	SecurityArtifacts *test.SecurityArtifacts `protobuf:"bytes,1,opt,name=security_artifacts,json=securityArtifacts,proto3" json:"security_artifacts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetSecurityArtifactsRequest) Reset() {
	*x = SetSecurityArtifactsRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecurityArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecurityArtifactsRequest) ProtoMessage() {}

func (x *SetSecurityArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecurityArtifactsRequest.ProtoReflect.Descriptor instead.
func (*SetSecurityArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{8}
}

func (x *SetSecurityArtifactsRequest) GetSecurityArtifacts() *test.SecurityArtifacts {
	if x != nil {
		return x.SecurityArtifacts
	}
	return nil
}

type SetSecurityArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecurityArtifactsResponse) Reset() {
	*x = SetSecurityArtifactsResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecurityArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecurityArtifactsResponse) ProtoMessage() {}

func (x *SetSecurityArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecurityArtifactsResponse.ProtoReflect.Descriptor instead.
func (*SetSecurityArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{9}
}

type GetBootzURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootzURLRequest) Reset() {
	*x = GetBootzURLRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootzURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootzURLRequest) ProtoMessage() {}

func (x *GetBootzURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootzURLRequest.ProtoReflect.Descriptor instead.
func (*GetBootzURLRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{10}
}

type GetBootzURLResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Bootz URL that the DUT should use to contact the Bootz SUT.
	// This URL will be of the format: bootz://<server_address>:<port>. For
	// example:
	// * IPv6: bootz://[2001:db8::1]:12345
	// * IPv4: bootz://192.168.1.1:12345
	BootzUrl      string `protobuf:"bytes,1,opt,name=bootz_url,json=bootzUrl,proto3" json:"bootz_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBootzURLResponse) Reset() {
	*x = GetBootzURLResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBootzURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBootzURLResponse) ProtoMessage() {}

func (x *GetBootzURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBootzURLResponse.ProtoReflect.Descriptor instead.
func (*GetBootzURLResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{11}
}

func (x *GetBootzURLResponse) GetBootzUrl() string {
	if x != nil {
		return x.BootzUrl
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{12}
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SubscribeResponse_GetBootstrapDataRequest
	//	*SubscribeResponse_ReportStatusRequest
	Event isSubscribeResponse_Event `protobuf_oneof:"event"`
	// The error, if any, that was returned to the DUT in response to this event.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeResponse) GetEvent() isSubscribeResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscribeResponse) GetGetBootstrapDataRequest() *bootz.GetBootstrapDataRequest {
	if x != nil {
		if x, ok := x.Event.(*SubscribeResponse_GetBootstrapDataRequest); ok {
			return x.GetBootstrapDataRequest
		}
	}
	return nil
}

func (x *SubscribeResponse) GetReportStatusRequest() *bootz.ReportStatusRequest {
	if x != nil {
		if x, ok := x.Event.(*SubscribeResponse_ReportStatusRequest); ok {
			return x.ReportStatusRequest
		}
	}
	return nil
}

func (x *SubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isSubscribeResponse_Event interface {
	isSubscribeResponse_Event()
}

type SubscribeResponse_GetBootstrapDataRequest struct {
	// The GetBootstrapDataRequest that the DUT sends to the Bootz SUT.
	GetBootstrapDataRequest *bootz.GetBootstrapDataRequest `protobuf:"bytes,1,opt,name=get_bootstrap_data_request,json=getBootstrapDataRequest,proto3,oneof"`
}

type SubscribeResponse_ReportStatusRequest struct {
	// The ReportStatusRequest that the DUT sends to the Bootz SUT.
	ReportStatusRequest *bootz.ReportStatusRequest `protobuf:"bytes,2,opt,name=report_status_request,json=reportStatusRequest,proto3,oneof"`
}

func (*SubscribeResponse_GetBootstrapDataRequest) isSubscribeResponse_Event() {}

func (*SubscribeResponse_ReportStatusRequest) isSubscribeResponse_Event() {}

type SetRecoveryDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The recovery data to be used by the Bootz SUT after the test is complete.
	RecoveryData  *test.DUTRecoveryData `protobuf:"bytes,1,opt,name=recovery_data,json=recoveryData,proto3" json:"recovery_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRecoveryDataRequest) Reset() {
	*x = SetRecoveryDataRequest{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRecoveryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecoveryDataRequest) ProtoMessage() {}

func (x *SetRecoveryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecoveryDataRequest.ProtoReflect.Descriptor instead.
func (*SetRecoveryDataRequest) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{14}
}

func (x *SetRecoveryDataRequest) GetRecoveryData() *test.DUTRecoveryData {
	if x != nil {
		return x.RecoveryData
	}
	return nil
}

type SetRecoveryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRecoveryDataResponse) Reset() {
	*x = SetRecoveryDataResponse{}
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRecoveryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecoveryDataResponse) ProtoMessage() {}

func (x *SetRecoveryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecoveryDataResponse.ProtoReflect.Descriptor instead.
func (*SetRecoveryDataResponse) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP(), []int{15}
}

var File_github_com_openconfig_bootz_server_tests_proto_sut_proto protoreflect.FileDescriptor

const file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDesc = "" +
	"\n" +
	"8github.com/openconfig/bootz/server/tests/proto/sut.proto\x12\x05bootz\x1a-github.com/openconfig/bootz/proto/bootz.proto\x1a9github.com/openconfig/bootz/server/tests/proto/test.proto\"\xbf\x01\n" +
	"\x12CreateLeaseRequest\x12#\n" +
	"\rmac_addresses\x18\x01 \x03(\tR\fmacAddresses\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x19\n" +
	"\bmask_len\x18\x03 \x01(\x05R\amaskLen\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\x120\n" +
	"\x14bootz_server_address\x18\x05 \x01(\tR\x12bootzServerAddress\"\x15\n" +
	"\x13CreateLeaseResponse\"9\n" +
	"\x12RemoveLeaseRequest\x12#\n" +
	"\rmac_addresses\x18\x01 \x03(\tR\fmacAddresses\"\x15\n" +
	"\x13RemoveLeaseResponse\"5\n" +
	"\rUploadRequest\x12$\n" +
	"\x05image\x18\x01 \x01(\v2\x0e.bootz.OSImageR\x05image\"<\n" +
	"\x0eUploadResponse\x12*\n" +
	"\x05image\x18\x01 \x01(\v2\x14.bootz.SoftwareImageR\x05image\"V\n" +
	"\x17SetBootstrapDataRequest\x12;\n" +
	"\x0ebootstrap_data\x18\x01 \x01(\v2\x14.bootz.BootstrapDataR\rbootstrapData\"\x1a\n" +
	"\x18SetBootstrapDataResponse\"f\n" +
	"\x1bSetSecurityArtifactsRequest\x12G\n" +
	"\x12security_artifacts\x18\x01 \x01(\v2\x18.bootz.SecurityArtifactsR\x11securityArtifacts\"\x1e\n" +
	"\x1cSetSecurityArtifactsResponse\"\x14\n" +
	"\x12GetBootzURLRequest\"2\n" +
	"\x13GetBootzURLResponse\x12\x1b\n" +
	"\tbootz_url\x18\x01 \x01(\tR\bbootzUrl\"\x12\n" +
	"\x10SubscribeRequest\"\xe3\x01\n" +
	"\x11SubscribeResponse\x12]\n" +
	"\x1aget_bootstrap_data_request\x18\x01 \x01(\v2\x1e.bootz.GetBootstrapDataRequestH\x00R\x17getBootstrapDataRequest\x12P\n" +
	"\x15report_status_request\x18\x02 \x01(\v2\x1a.bootz.ReportStatusRequestH\x00R\x13reportStatusRequest\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\a\n" +
	"\x05event\"U\n" +
	"\x16SetRecoveryDataRequest\x12;\n" +
	"\rrecovery_data\x18\x01 \x01(\v2\x16.bootz.DUTRecoveryDataR\frecoveryData\"\x19\n" +
	"\x17SetRecoveryDataResponse2\x9d\x01\n" +
	"\vDHCPService\x12F\n" +
	"\vCreateLease\x12\x19.bootz.CreateLeaseRequest\x1a\x1a.bootz.CreateLeaseResponse\"\x00\x12F\n" +
	"\vRemoveLease\x12\x19.bootz.RemoveLeaseRequest\x1a\x1a.bootz.RemoveLeaseResponse\"\x002G\n" +
	"\fImageService\x127\n" +
	"\x06Upload\x12\x14.bootz.UploadRequest\x1a\x15.bootz.UploadResponse\"\x002\xab\x03\n" +
	"\x0fBootzController\x12U\n" +
	"\x10SetBootstrapData\x12\x1e.bootz.SetBootstrapDataRequest\x1a\x1f.bootz.SetBootstrapDataResponse\"\x00\x12a\n" +
	"\x14SetSecurityArtifacts\x12\".bootz.SetSecurityArtifactsRequest\x1a#.bootz.SetSecurityArtifactsResponse\"\x00\x12R\n" +
	"\x0fSetRecoveryData\x12\x1d.bootz.SetRecoveryDataRequest\x1a\x1e.bootz.SetRecoveryDataResponse\"\x00\x12F\n" +
	"\vGetBootzURL\x12\x19.bootz.GetBootzURLRequest\x1a\x1a.bootz.GetBootzURLResponse\"\x00\x12B\n" +
	"\tSubscribe\x12\x17.bootz.SubscribeRequest\x1a\x18.bootz.SubscribeResponse\"\x000\x01B4Z2github.com/openconfig/bootz/server/tests/proto/sutb\x06proto3"

var (
	file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescOnce sync.Once
	file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescData []byte
)

func file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDesc), len(file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDesc)))
	})
	return file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDescData
}

var file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_github_com_openconfig_bootz_server_tests_proto_sut_proto_goTypes = []any{
	(*CreateLeaseRequest)(nil),            // 0: bootz.CreateLeaseRequest
	(*CreateLeaseResponse)(nil),           // 1: bootz.CreateLeaseResponse
	(*RemoveLeaseRequest)(nil),            // 2: bootz.RemoveLeaseRequest
	(*RemoveLeaseResponse)(nil),           // 3: bootz.RemoveLeaseResponse
	(*UploadRequest)(nil),                 // 4: bootz.UploadRequest
	(*UploadResponse)(nil),                // 5: bootz.UploadResponse
	(*SetBootstrapDataRequest)(nil),       // 6: bootz.SetBootstrapDataRequest
	(*SetBootstrapDataResponse)(nil),      // 7: bootz.SetBootstrapDataResponse
	(*SetSecurityArtifactsRequest)(nil),   // 8: bootz.SetSecurityArtifactsRequest
	(*SetSecurityArtifactsResponse)(nil),  // 9: bootz.SetSecurityArtifactsResponse
	(*GetBootzURLRequest)(nil),            // 10: bootz.GetBootzURLRequest
	(*GetBootzURLResponse)(nil),           // 11: bootz.GetBootzURLResponse
	(*SubscribeRequest)(nil),              // 12: bootz.SubscribeRequest
	(*SubscribeResponse)(nil),             // 13: bootz.SubscribeResponse
	(*SetRecoveryDataRequest)(nil),        // 14: bootz.SetRecoveryDataRequest
	(*SetRecoveryDataResponse)(nil),       // 15: bootz.SetRecoveryDataResponse
	(*test.OSImage)(nil),                  // 16: bootz.OSImage
	(*bootz.SoftwareImage)(nil),           // 17: bootz.SoftwareImage
	(*test.BootstrapData)(nil),            // 18: bootz.BootstrapData
	(*test.SecurityArtifacts)(nil),        // 19: bootz.SecurityArtifacts
	(*bootz.GetBootstrapDataRequest)(nil), // 20: bootz.GetBootstrapDataRequest
	(*bootz.ReportStatusRequest)(nil),     // 21: bootz.ReportStatusRequest
	(*test.DUTRecoveryData)(nil),          // 22: bootz.DUTRecoveryData
}
var file_github_com_openconfig_bootz_server_tests_proto_sut_proto_depIdxs = []int32{
	16, // 0: bootz.UploadRequest.image:type_name -> bootz.OSImage
	17, // 1: bootz.UploadResponse.image:type_name -> bootz.SoftwareImage
	18, // 2: bootz.SetBootstrapDataRequest.bootstrap_data:type_name -> bootz.BootstrapData
	19, // 3: bootz.SetSecurityArtifactsRequest.security_artifacts:type_name -> bootz.SecurityArtifacts
	20, // 4: bootz.SubscribeResponse.get_bootstrap_data_request:type_name -> bootz.GetBootstrapDataRequest
	21, // 5: bootz.SubscribeResponse.report_status_request:type_name -> bootz.ReportStatusRequest
	22, // 6: bootz.SetRecoveryDataRequest.recovery_data:type_name -> bootz.DUTRecoveryData
	0,  // 7: bootz.DHCPService.CreateLease:input_type -> bootz.CreateLeaseRequest
	2,  // 8: bootz.DHCPService.RemoveLease:input_type -> bootz.RemoveLeaseRequest
	4,  // 9: bootz.ImageService.Upload:input_type -> bootz.UploadRequest
	6,  // 10: bootz.BootzController.SetBootstrapData:input_type -> bootz.SetBootstrapDataRequest
	8,  // 11: bootz.BootzController.SetSecurityArtifacts:input_type -> bootz.SetSecurityArtifactsRequest
	14, // 12: bootz.BootzController.SetRecoveryData:input_type -> bootz.SetRecoveryDataRequest
	10, // 13: bootz.BootzController.GetBootzURL:input_type -> bootz.GetBootzURLRequest
	12, // 14: bootz.BootzController.Subscribe:input_type -> bootz.SubscribeRequest
	1,  // 15: bootz.DHCPService.CreateLease:output_type -> bootz.CreateLeaseResponse
	3,  // 16: bootz.DHCPService.RemoveLease:output_type -> bootz.RemoveLeaseResponse
	5,  // 17: bootz.ImageService.Upload:output_type -> bootz.UploadResponse
	7,  // 18: bootz.BootzController.SetBootstrapData:output_type -> bootz.SetBootstrapDataResponse
	9,  // 19: bootz.BootzController.SetSecurityArtifacts:output_type -> bootz.SetSecurityArtifactsResponse
	15, // 20: bootz.BootzController.SetRecoveryData:output_type -> bootz.SetRecoveryDataResponse
	11, // 21: bootz.BootzController.GetBootzURL:output_type -> bootz.GetBootzURLResponse
	13, // 22: bootz.BootzController.Subscribe:output_type -> bootz.SubscribeResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_bootz_server_tests_proto_sut_proto_init() }
func file_github_com_openconfig_bootz_server_tests_proto_sut_proto_init() {
	if File_github_com_openconfig_bootz_server_tests_proto_sut_proto != nil {
		return
	}
	file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes[13].OneofWrappers = []any{
		(*SubscribeResponse_GetBootstrapDataRequest)(nil),
		(*SubscribeResponse_ReportStatusRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDesc), len(file_github_com_openconfig_bootz_server_tests_proto_sut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_github_com_openconfig_bootz_server_tests_proto_sut_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_bootz_server_tests_proto_sut_proto_depIdxs,
		MessageInfos:      file_github_com_openconfig_bootz_server_tests_proto_sut_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_bootz_server_tests_proto_sut_proto = out.File
	file_github_com_openconfig_bootz_server_tests_proto_sut_proto_goTypes = nil
	file_github_com_openconfig_bootz_server_tests_proto_sut_proto_depIdxs = nil
}

