// Copyright 2026 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: github.com/openconfig/bootz/server/tests/proto/sut.proto

package sut

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DHCPService_CreateLease_FullMethodName = "/bootz.DHCPService/CreateLease"
	DHCPService_RemoveLease_FullMethodName = "/bootz.DHCPService/RemoveLease"
)

// DHCPServiceClient is the client API for DHCPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DHCP Service
// The DHCP service is responsible for managing DHCP leases for the DUT and
// responding to DHCP requests.
type DHCPServiceClient interface {
	// CreateLease creates a DHCP lease for the DUT.
	CreateLease(ctx context.Context, in *CreateLeaseRequest, opts ...grpc.CallOption) (*CreateLeaseResponse, error)
	// RemoveLease deletes a DHCP lease for the DUT.
	RemoveLease(ctx context.Context, in *RemoveLeaseRequest, opts ...grpc.CallOption) (*RemoveLeaseResponse, error)
}

type dHCPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDHCPServiceClient(cc grpc.ClientConnInterface) DHCPServiceClient {
	return &dHCPServiceClient{cc}
}

func (c *dHCPServiceClient) CreateLease(ctx context.Context, in *CreateLeaseRequest, opts ...grpc.CallOption) (*CreateLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLeaseResponse)
	err := c.cc.Invoke(ctx, DHCPService_CreateLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHCPServiceClient) RemoveLease(ctx context.Context, in *RemoveLeaseRequest, opts ...grpc.CallOption) (*RemoveLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveLeaseResponse)
	err := c.cc.Invoke(ctx, DHCPService_RemoveLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DHCPServiceServer is the server API for DHCPService service.
// All implementations must embed UnimplementedDHCPServiceServer
// for forward compatibility.
//
// DHCP Service
// The DHCP service is responsible for managing DHCP leases for the DUT and
// responding to DHCP requests.
type DHCPServiceServer interface {
	// CreateLease creates a DHCP lease for the DUT.
	CreateLease(context.Context, *CreateLeaseRequest) (*CreateLeaseResponse, error)
	// RemoveLease deletes a DHCP lease for the DUT.
	RemoveLease(context.Context, *RemoveLeaseRequest) (*RemoveLeaseResponse, error)
	mustEmbedUnimplementedDHCPServiceServer()
}

// UnimplementedDHCPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDHCPServiceServer struct{}

func (UnimplementedDHCPServiceServer) CreateLease(context.Context, *CreateLeaseRequest) (*CreateLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLease not implemented")
}
func (UnimplementedDHCPServiceServer) RemoveLease(context.Context, *RemoveLeaseRequest) (*RemoveLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveLease not implemented")
}
func (UnimplementedDHCPServiceServer) mustEmbedUnimplementedDHCPServiceServer() {}
func (UnimplementedDHCPServiceServer) testEmbeddedByValue()                     {}

// UnsafeDHCPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DHCPServiceServer will
// result in compilation errors.
type UnsafeDHCPServiceServer interface {
	mustEmbedUnimplementedDHCPServiceServer()
}

func RegisterDHCPServiceServer(s grpc.ServiceRegistrar, srv DHCPServiceServer) {
	// If the following call panics, it indicates UnimplementedDHCPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DHCPService_ServiceDesc, srv)
}

func _DHCPService_CreateLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHCPServiceServer).CreateLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHCPService_CreateLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHCPServiceServer).CreateLease(ctx, req.(*CreateLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHCPService_RemoveLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHCPServiceServer).RemoveLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHCPService_RemoveLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHCPServiceServer).RemoveLease(ctx, req.(*RemoveLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DHCPService_ServiceDesc is the grpc.ServiceDesc for DHCPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DHCPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bootz.DHCPService",
	HandlerType: (*DHCPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLease",
			Handler:    _DHCPService_CreateLease_Handler,
		},
		{
			MethodName: "RemoveLease",
			Handler:    _DHCPService_RemoveLease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openconfig/bootz/server/tests/proto/sut.proto",
}

const (
	ImageService_Upload_FullMethodName = "/bootz.ImageService/Upload"
)

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Image Service
// The Image Service provides an interface to upload images.
type ImageServiceClient interface {
	// Upload makes the provided OS image available to the Bootz SUT for
	// download during the Bootz test.
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, ImageService_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility.
//
// Image Service
// The Image Service provides an interface to upload images.
type ImageServiceServer interface {
	// Upload makes the provided OS image available to the Bootz SUT for
	// download during the Bootz test.
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageServiceServer struct{}

func (UnimplementedImageServiceServer) Upload(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}
func (UnimplementedImageServiceServer) testEmbeddedByValue()                      {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	// If the following call panics, it indicates UnimplementedImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bootz.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _ImageService_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openconfig/bootz/server/tests/proto/sut.proto",
}

const (
	BootzController_SetBootstrapData_FullMethodName     = "/bootz.BootzController/SetBootstrapData"
	BootzController_SetSecurityArtifacts_FullMethodName = "/bootz.BootzController/SetSecurityArtifacts"
	BootzController_SetRecoveryData_FullMethodName      = "/bootz.BootzController/SetRecoveryData"
	BootzController_GetBootzURL_FullMethodName          = "/bootz.BootzController/GetBootzURL"
	BootzController_Subscribe_FullMethodName            = "/bootz.BootzController/Subscribe"
)

// BootzControllerClient is the client API for BootzController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BootzController Service
// The BootzController service provides an interface to configure the responses
// that will be returned by the Bootz SUT. Ideally, this RPC service is hosted
// on the same SUT as the device-facing Bootz service but that is not a
// requirement.
type BootzControllerClient interface {
	// Sets the bootstrap data that the Bootz SUT should use during the Bootz test
	// when replying to the DUT.
	SetBootstrapData(ctx context.Context, in *SetBootstrapDataRequest, opts ...grpc.CallOption) (*SetBootstrapDataResponse, error)
	// Sets the security artifacts that the Bootz SUT should use during the Bootz
	// test when replying to the DUT.
	SetSecurityArtifacts(ctx context.Context, in *SetSecurityArtifactsRequest, opts ...grpc.CallOption) (*SetSecurityArtifactsResponse, error)
	// SetRecoveryData sets the recovery data that the Bootz SUT should use after
	// the test is complete.
	SetRecoveryData(ctx context.Context, in *SetRecoveryDataRequest, opts ...grpc.CallOption) (*SetRecoveryDataResponse, error)
	// Returns the Bootz URL that the DUT should use to contact the Bootz SUT.
	GetBootzURL(ctx context.Context, in *GetBootzURLRequest, opts ...grpc.CallOption) (*GetBootzURLResponse, error)
	// Subscribe allows the test to subscribe to events from the Bootz SUT.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
}

type bootzControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewBootzControllerClient(cc grpc.ClientConnInterface) BootzControllerClient {
	return &bootzControllerClient{cc}
}

func (c *bootzControllerClient) SetBootstrapData(ctx context.Context, in *SetBootstrapDataRequest, opts ...grpc.CallOption) (*SetBootstrapDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBootstrapDataResponse)
	err := c.cc.Invoke(ctx, BootzController_SetBootstrapData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootzControllerClient) SetSecurityArtifacts(ctx context.Context, in *SetSecurityArtifactsRequest, opts ...grpc.CallOption) (*SetSecurityArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecurityArtifactsResponse)
	err := c.cc.Invoke(ctx, BootzController_SetSecurityArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootzControllerClient) SetRecoveryData(ctx context.Context, in *SetRecoveryDataRequest, opts ...grpc.CallOption) (*SetRecoveryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRecoveryDataResponse)
	err := c.cc.Invoke(ctx, BootzController_SetRecoveryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootzControllerClient) GetBootzURL(ctx context.Context, in *GetBootzURLRequest, opts ...grpc.CallOption) (*GetBootzURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootzURLResponse)
	err := c.cc.Invoke(ctx, BootzController_GetBootzURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootzControllerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BootzController_ServiceDesc.Streams[0], BootzController_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BootzController_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

// BootzControllerServer is the server API for BootzController service.
// All implementations must embed UnimplementedBootzControllerServer
// for forward compatibility.
//
// BootzController Service
// The BootzController service provides an interface to configure the responses
// that will be returned by the Bootz SUT. Ideally, this RPC service is hosted
// on the same SUT as the device-facing Bootz service but that is not a
// requirement.
type BootzControllerServer interface {
	// Sets the bootstrap data that the Bootz SUT should use during the Bootz test
	// when replying to the DUT.
	SetBootstrapData(context.Context, *SetBootstrapDataRequest) (*SetBootstrapDataResponse, error)
	// Sets the security artifacts that the Bootz SUT should use during the Bootz
	// test when replying to the DUT.
	SetSecurityArtifacts(context.Context, *SetSecurityArtifactsRequest) (*SetSecurityArtifactsResponse, error)
	// SetRecoveryData sets the recovery data that the Bootz SUT should use after
	// the test is complete.
	SetRecoveryData(context.Context, *SetRecoveryDataRequest) (*SetRecoveryDataResponse, error)
	// Returns the Bootz URL that the DUT should use to contact the Bootz SUT.
	GetBootzURL(context.Context, *GetBootzURLRequest) (*GetBootzURLResponse, error)
	// Subscribe allows the test to subscribe to events from the Bootz SUT.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	mustEmbedUnimplementedBootzControllerServer()
}

// UnimplementedBootzControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBootzControllerServer struct{}

func (UnimplementedBootzControllerServer) SetBootstrapData(context.Context, *SetBootstrapDataRequest) (*SetBootstrapDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBootstrapData not implemented")
}
func (UnimplementedBootzControllerServer) SetSecurityArtifacts(context.Context, *SetSecurityArtifactsRequest) (*SetSecurityArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSecurityArtifacts not implemented")
}
func (UnimplementedBootzControllerServer) SetRecoveryData(context.Context, *SetRecoveryDataRequest) (*SetRecoveryDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRecoveryData not implemented")
}
func (UnimplementedBootzControllerServer) GetBootzURL(context.Context, *GetBootzURLRequest) (*GetBootzURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBootzURL not implemented")
}
func (UnimplementedBootzControllerServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBootzControllerServer) mustEmbedUnimplementedBootzControllerServer() {}
func (UnimplementedBootzControllerServer) testEmbeddedByValue()                         {}

// UnsafeBootzControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BootzControllerServer will
// result in compilation errors.
type UnsafeBootzControllerServer interface {
	mustEmbedUnimplementedBootzControllerServer()
}

func RegisterBootzControllerServer(s grpc.ServiceRegistrar, srv BootzControllerServer) {
	// If the following call panics, it indicates UnimplementedBootzControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BootzController_ServiceDesc, srv)
}

func _BootzController_SetBootstrapData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBootstrapDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootzControllerServer).SetBootstrapData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootzController_SetBootstrapData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootzControllerServer).SetBootstrapData(ctx, req.(*SetBootstrapDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BootzController_SetSecurityArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecurityArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootzControllerServer).SetSecurityArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootzController_SetSecurityArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootzControllerServer).SetSecurityArtifacts(ctx, req.(*SetSecurityArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BootzController_SetRecoveryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRecoveryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootzControllerServer).SetRecoveryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootzController_SetRecoveryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootzControllerServer).SetRecoveryData(ctx, req.(*SetRecoveryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BootzController_GetBootzURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootzURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootzControllerServer).GetBootzURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootzController_GetBootzURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootzControllerServer).GetBootzURL(ctx, req.(*GetBootzURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BootzController_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BootzControllerServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BootzController_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

// BootzController_ServiceDesc is the grpc.ServiceDesc for BootzController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BootzController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bootz.BootzController",
	HandlerType: (*BootzControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBootstrapData",
			Handler:    _BootzController_SetBootstrapData_Handler,
		},
		{
			MethodName: "SetSecurityArtifacts",
			Handler:    _BootzController_SetSecurityArtifacts_Handler,
		},
		{
			MethodName: "SetRecoveryData",
			Handler:    _BootzController_SetRecoveryData_Handler,
		},
		{
			MethodName: "GetBootzURL",
			Handler:    _BootzController_GetBootzURL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _BootzController_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/openconfig/bootz/server/tests/proto/sut.proto",
}