// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: github.com/openconfig/bootz/dhcp/proto/dhcpconfig.proto

package dhcpconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Dns           []string               `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	BootzUrls     []string               `protobuf:"bytes,3,rep,name=bootz_urls,json=bootzUrls,proto3" json:"bootz_urls,omitempty"`
	Records       []*Record              `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Config) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *Config) GetBootzUrls() []string {
	if x != nil {
		return x.BootzUrls
	}
	return nil
}

func (x *Config) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       string                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *Record) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Record) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

var File_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto protoreflect.FileDescriptor

const file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDesc = "" +
	"\n" +
	"7github.com/openconfig/bootz/dhcp/proto/dhcpconfig.proto\x12\n" +
	"dhcpconfig\"\x85\x01\n" +
	"\x06Config\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x10\n" +
	"\x03dns\x18\x02 \x03(\tR\x03dns\x12\x1d\n" +
	"\n" +
	"bootz_urls\x18\x03 \x03(\tR\tbootzUrls\x12,\n" +
	"\arecords\x18\x04 \x03(\v2\x12.dhcpconfig.RecordR\arecords\"L\n" +
	"\x06Record\x12\x18\n" +
	"\amachine\x18\x01 \x01(\tR\amachine\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agatewayB3Z1github.com/openconfig/bootz/dhcp/proto/dhcpconfigb\x06proto3"

var (
	file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescOnce sync.Once
	file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescData []byte
)

func file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescGZIP() []byte {
	file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescOnce.Do(func() {
		file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDesc), len(file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDesc)))
	})
	return file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDescData
}

var file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_goTypes = []any{
	(*Config)(nil), // 0: dhcpconfig.Config
	(*Record)(nil), // 1: dhcpconfig.Record
}
var file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_depIdxs = []int32{
	1, // 0: dhcpconfig.Config.records:type_name -> dhcpconfig.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_init() }
func file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_init() {
	if File_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDesc), len(file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_goTypes,
		DependencyIndexes: file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_depIdxs,
		MessageInfos:      file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_msgTypes,
	}.Build()
	File_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto = out.File
	file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_goTypes = nil
	file_github_com_openconfig_bootz_dhcp_proto_dhcpconfig_proto_depIdxs = nil
}
